# Generated by Django 4.1 on 2022-10-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app1", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="sexo",
            field=models.CharField(
                choices=[("F", "Femenino"), ("M", "Masculino")],
                default="F",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="nombre",
            field=models.CharField(max_length=30, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="proveedor", name="telefono", field=models.IntegerField()
        ),
    ]
