# Generated by Django 4.1 on 2022-09-16 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("app1", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="producto_venta",
            name="Producto",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.producto",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producto_venta",
            name="Venta",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="app1.venta"
            ),
            preserve_default=False,
        ),
    ]
