# Generated by Django 4.1 on 2022-10-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app1", "0002_proveedor_sexo_alter_proveedor_nombre_and_more")]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=100)),
                ("Clientes", models.ManyToManyField(to="app1.cliente")),
            ],
            options={"ordering": ["headline"]},
        )
    ]
